
apiVersion: v1
kind: Service
metadata:
  name: scopepluswar
  labels:
    app: scopepluswar
spec:
  ports:
    - port: 9080
  selector:
    app: scopepluswar
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: scopepluswar
  name: scopepluswar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scopepluswar
    spec:
      containers:
      - image: mycluster.icp:8500/default/scopepluswar:latest
        name: scopepluswar
        ports:
        - containerPort: 9080
          protocol: TCP
